# config.yml

server:
  host: 127.0.0.1
  port: 8080
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
ethereum_url:
  "https://ethereum-rpc.publicnode.com"
worker_ticker_duration:
  1s